retargeting:
  type: position
  urdf_path: fourier_hand/fourier_right_hand.urdf

  target_joint_names: [ 'R_pinky_proximal_joint', 'R_ring_proximal_joint', 'R_middle_proximal_joint', 'R_index_proximal_joint',
                        'R_thumb_proximal_pitch_joint', 'R_thumb_proximal_yaw_joint' ]
  target_link_names: [ "R_thumb_tip_link",  "R_index_tip_link", "R_middle_tip_link", "R_ring_tip_link", "R_pinky_tip_link", "R_hand_base_link" ]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 0 ]
  add_dummy_free_joint: True

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1

  # To ignore the mimic joint tags in the URDF, set it to True
  ignore_mimic_joint: False
