# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_transfer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14image_transfer.proto\"K\n\x10ImageDataRequest\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\x12\x14\n\x0cright_action\x18\x02 \x03(\x02\x12\x13\n\x0bleft_action\x18\x03 \x03(\x02\"&\n\x10\x46loatDataRequest\x12\x12\n\nfloat_data\x18\x01 \x01(\x02\"\xbc\x01\n\x11ImageDataResponse\x12\x12\n\nimage_body\x18\x01 \x01(\x0c\x12\x17\n\x0fimage_head_left\x18\x02 \x01(\x0c\x12\x18\n\x10image_head_right\x18\x03 \x01(\x0c\x12\x16\n\x0eright_arm_pose\x18\x04 \x03(\x02\x12\x18\n\x10right_hand_angle\x18\x05 \x03(\x02\x12\x15\n\rleft_arm_pose\x18\x06 \x03(\x02\x12\x17\n\x0fleft_hand_angle\x18\x07 \x03(\x02\x32L\n\rImageTransfer\x12;\n\x12UploadImageAndData\x12\x11.ImageDataRequest\x1a\x12.ImageDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEDATAREQUEST']._serialized_start=24
  _globals['_IMAGEDATAREQUEST']._serialized_end=99
  _globals['_FLOATDATAREQUEST']._serialized_start=101
  _globals['_FLOATDATAREQUEST']._serialized_end=139
  _globals['_IMAGEDATARESPONSE']._serialized_start=142
  _globals['_IMAGEDATARESPONSE']._serialized_end=330
  _globals['_IMAGETRANSFER']._serialized_start=332
  _globals['_IMAGETRANSFER']._serialized_end=408
# @@protoc_insertion_point(module_scope)
