# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_transfer_pb2 as image__transfer__pb2


GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

# if _version_not_supported:
    # GRPC_VERSION = grpc.__version__
    # raise RuntimeError(
    #     f'The grpc package installed is at version {GRPC_VERSION},'
    #     + f' but the generated code in image_transfer_pb2_grpc.py depends on'
    #     + f' grpcio>={GRPC_GENERATED_VERSION}.'
    #     + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
    #     + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    # )


class ImageTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImageAndData = channel.unary_unary(
                '/ImageTransfer/UploadImageAndData',
                request_serializer=image__transfer__pb2.ImageDataRequest.SerializeToString,
                response_deserializer=image__transfer__pb2.ImageDataResponse.FromString,
                _registered_method=True)


class ImageTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadImageAndData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImageAndData': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImageAndData,
                    request_deserializer=image__transfer__pb2.ImageDataRequest.FromString,
                    response_serializer=image__transfer__pb2.ImageDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadImageAndData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageTransfer/UploadImageAndData',
            image__transfer__pb2.ImageDataRequest.SerializeToString,
            image__transfer__pb2.ImageDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
